LIKELION-Android-Bootcamp-4th/AOS-04-officeShoppingMall

lib/core/widgets/custom_app_bar.dart
lib/main.dart
pubspec.yaml

- 커스텀 앱 바 구현
- svg 벡터 이미지 투명화
- [] 기능 정상 동작 확인

[Bug] 커스텀 앱바 아이콘 오류

---

lib/core/constants/api_endpoints.dart
lib/core/constants/app_routes.dart
lib/core/services/api_client.dart
lib/core/services/auth_service.dart
lib/feature/home/ui/HomeScreen.dart
lib/main.dart
pubspec.lock
pubspec.yaml
test/widget_test.dart

- dio_logger 추가
- swagger 와 통신을 위해 기본 헤더 및 로그를 남기는 ApiClient 구현
- 로그인 관련 서비스인 AuthService 구현
- api 보안이나 상수화는 추후 추가 필요

[Feature] Swagger와 통신하는 Api 클라이언트 구현

---

lib/core/constants/app_colors.dart
lib/core/theme/app_colors.dart
lib/core/theme/theme.dart
lib/core/widgets/custom_app_bar.dart
lib/main.dart

- 앱 내부에서 사용하는 컬러 지정
- 앱 내 컴포넌트의 테마 지정
- 앱 내에서 사용할 폰트 지정

[Feature] 앱 테마 설정

---

lib/core/constants/api_endpoints.dart
lib/core/services/auth_service.dart
lib/feature/auth/ui/signup_form.dart
lib/feature/home/ui/search_recent_keyword.dart

- 회원가입  기능 추가
- 테스트 완료
- 그외 오타 수정
x

[Feature] 회원가입 기능 추가

---

lib/core/widgets/app_bar_actions.dart
lib/feature/auth/ui/login_screen.dart
lib/feature/auth/ui/signup_screen.dart
lib/feature/category/ui/category_screen.dart
lib/feature/home/ui/home_content_products.dart
lib/feature/home/ui/home_screen.dart
lib/feature/mypage/ui/mypage_screen.dart
lib/feature/preference/ui/preference_content_list.dart
lib/feature/preference/ui/preference_screen.dart

- 앱바 actions 추출
- 다이얼로그 테마 적용 등

[Refactor] 앱바 및 다이어로그 리팩터링

---

lib/core/constants/api_endpoints.dart
lib/core/services/api_client.dart
lib/core/services/auth_service.dart

- 주 사용 api 추가
- Api.auth.login 처럼 쉽게 접근 가능하도록 변경
- 몇몇 api 에 설명 문서 작성

[Feature] Api 엔드포인트 추가 및 변경

---

lib/feature/auth/bloc/auth_provider.dart
lib/feature/auth/ui/login_form.dart
lib/main.dart

[feature] 로그인 상태 추가

---

lib/app_router.dart
lib/core/constants/app_routes.dart
lib/feature/setting/ui/dest_setting_screen.dart
lib/feature/setting/ui/user_info_tab.dart

[Feature] 배송지 설정 화면 구현

---

lib/core/widgets/app_bar/custom_app_bar.dart
lib/feature/category/ui/category_screen.dart
lib/feature/mypage/ui/mypage_screen.dart
lib/feature/preference/ui/preference_screen.dart

- 카테고리, 좋아요(찜), 마이페이지 화면의 앱바에서 뜨던 leading 제거
- autoLeading 아이콘 안뜨게 설정

[Refactor] 일부화면 앱바의 leading 제거

---

lib/core/constants/app_routes.dart
lib/feature/cart/data/product_list_item.dart
lib/feature/cart/ui/cart_screen.dart
lib/feature/cart/ui/delivery_navigation.dart
lib/feature/cart/ui/order_detail_screen.dart
lib/feature/review/data/review_list.dart
lib/feature/review/ui/review_screen.dart

[Refactor] 상품 리스트 UI 수정

---

lib/feature/review/presentation/review_detail_screen.dart
lib/feature/review/presentation/review_screen.dart
lib/feature/review/presentation/widgets/add_review_content.dart
lib/feature/review/presentation/widgets/review_writable_tab.dart
lib/feature/review/presentation/widgets/review_written_tab.dart

[Feature] 리뷰 확인 화면 UI 추가 및 수정

---

lib/core/data/models/dto/user_dto.dart
lib/core/data/models/entity/user.dart
lib/feature/setting/presentation/widgets/user_info_tab.dart

- 변수명 가독성 패치
- User Entity 에 toJson 값 변경 (phone, address)

[Fix] setting 관련 fix

---

lib/core/constants/api_endpoints.dart

[Feature] api 엔드포인트 수정 및 추가

---

lib/feature/category/presentation/widgets/category_content_list.dart
lib/feature/home/presentation/widgets/home_content_products.dart
lib/feature/preference/presentation/widgets/preference_content_list.dart

- 카테고리 타이틀 탭 선택시 해당 페이지로 이동하도록 구현
- ~~상세 선택은 언제했댐..~~

[Feature] category 타이틀 탭 이벤트 구현

---

lib/core/utils/extension.dart
lib/feature/preference/data/preference_service.dart
lib/feature/preference/domain/preference_repository.dart
lib/feature/preference/preference_module.dart
lib/feature/preference/presentation/viewmodel/preference_viewmodel.dart
lib/feature/preference/presentation/widgets/preference_content_count_text.dart
lib/feature/preference/presentation/widgets/preference_content_list.dart
lib/main.dart

- 좋아요 관련 아키텍쳐 구현
- UI 와 데이터 연결
- ▲ 기능 정상 동작 확인
- 현재 좋아요 상품이 없어 보이진 않으나 처음 물건 로드 시 같이 불러와지는 것으로 파악됨
- 추가로 null 이나 오류가 아닌 총 0개로 뜨는 것으로 보아 동작은 되는 것 같음

[Feature] preference 네트워킹 성공

---

lib/core/data/models/dto/user_dto.dart
lib/core/data/models/entity/user.dart
lib/feature/mypage/presentation/widgets/mypage_content_user_card.dart
lib/feature/setting/data/setting_service.dart
lib/feature/setting/domain/setting_repository.dart
lib/feature/setting/presentation/setting_screen.dart
lib/feature/setting/presentation/viewmodel/setting_viewmodel.dart
lib/feature/setting/presentation/widgets/user_info_tab.dart

- 프로필 업로드를 위해 이미지를 multipart 로 변경
- 서버와 통신은 성공했으나 이미지 띄우기는 진전이 없음.
- 아래는 이미지를 서버에 보내 제대로 인식이 된 상태(아마도) 
- 이미지 띄우는 것에 대해 이슈 올릴 예정 
- 이번엔 이미지가 바로 안뜨는 이슈...

[Feature]  setting 프로필 업로드 관련

---

lib/feature/home/presentation/widgets/home_content_products.dart

[Feature] home 화면 아이템 리스트 출력

---

lib/feature/product/presentation/viewmodel/product_list_viewmodel.dart
lib/feature/product/presentation/widgets/product_list_content.dart
lib/feature/search/data/search_service.dart
lib/feature/search/domain/search_repository.dart
lib/feature/search/presentation/search_screen.dart
lib/feature/search/presentation/viewmodel/search_viewmodel.dart

- 검색할 때마다 이전 검색 화면을 받아오는 문제 해결
- 검색하면 검색 결과 아이템들을 받아오지 못하던 문제 해결
- 검색결과일 경우, 상품리스트 화면에서 카테고리명이 표시되지 않게 변경
- 검색 로딩 중에 인디케이터 표시 
https://github.com/user-attachments/assets/f3fa6e68-838e-40be-82f5-0e5542c8c669

[Fix] 검색 기능 버그 픽스

---

lib/core/constants/api_endpoints.dart
lib/core/data/models/dto/toggle_favorite_response.dart
lib/core/data/models/entity/product.dart
lib/feature/home/data/home_service.dart
lib/feature/home/domain/home_repository.dart
lib/feature/home/presentation/home_screen.dart
lib/feature/home/presentation/viewmodel/home_viewmodel.dart
lib/feature/home/presentation/widgets/home_content_products.dart
lib/feature/order/presentation/order_detail_screen.dart
lib/feature/payment/payment_screen.dart
lib/feature/payment/presentaion/widgets/payment_content.dart
lib/feature/preference/presentation/viewmodel/preference_viewmodel.dart
lib/feature/product/domain/product_repository_impl.dart
lib/feature/product/domain/repository/product_repository.dart
lib/feature/product/presentation/viewmodel/product_list_viewmodel.dart
lib/feature/product/presentation/viewmodel/product_viewmodel.dart
lib/feature/product/presentation/widgets/product_detail_content.dart
lib/feature/product/presentation/widgets/product_item.dart
lib/feature/product/presentation/widgets/product_review_content.dart
lib/feature/review/presentation/viewmodel/review_model.dart
lib/feature/review/presentation/widgets/add_review_content.dart
lib/feature/search/domain/search_repository.dart
lib/feature/search/presentation/viewmodel/search_viewmodel.dart
lib/feature/setting/presentation/viewmodel/setting_viewmodel.dart
lib/main.dart

- 공지사항 api 엔드포인트 추가
- ~~브랜치 잘못파서 홈화면 내용 그대로 있네요..~~

[Feature] 공지사항 api 엔드포인트 추가

---

lib/core/data/models/dto/toggle_favorite_response.dart
lib/core/data/models/entity/product.dart
lib/feature/home/data/home_service.dart
lib/feature/home/domain/home_repository.dart
lib/feature/home/presentation/home_screen.dart
lib/feature/home/presentation/viewmodel/home_viewmodel.dart
lib/feature/home/presentation/widgets/home_content_products.dart
lib/feature/order/presentation/order_detail_screen.dart
lib/feature/payment/payment_screen.dart
lib/feature/payment/presentaion/widgets/payment_content.dart
lib/feature/preference/presentation/viewmodel/preference_viewmodel.dart
lib/feature/product/domain/product_repository_impl.dart
lib/feature/product/domain/repository/product_repository.dart
lib/feature/product/presentation/viewmodel/product_list_viewmodel.dart
lib/feature/product/presentation/viewmodel/product_viewmodel.dart
lib/feature/product/presentation/widgets/product_detail_content.dart
lib/feature/product/presentation/widgets/product_item.dart
lib/feature/product/presentation/widgets/product_review_content.dart
lib/feature/review/presentation/viewmodel/review_model.dart
lib/feature/review/presentation/widgets/add_review_content.dart
lib/feature/search/domain/search_repository.dart
lib/feature/search/presentation/viewmodel/search_viewmodel.dart
lib/feature/setting/presentation/viewmodel/setting_viewmodel.dart
lib/main.dart

- ProductDTO 를 사용하던 기능들 일부 Product Entity 로 변경
- Swagger 랑 다른 응답을 처리하기 위한 ToggleFavoriteResponse 구현
- 홈 화면에서 결제 완료까지 특별한 실행되도록 수정 및 이미지 삽입
- 홈 화면에서 좋아요 시 좋아요가 반영되도록 구현 등
- 내일은 좋아요 화면 상품 출력 오류 수정 진행 예정

[Feature] home 스크린 관련 구현 및 수정

---

lib/feature/auth/data/signup_response.dart
lib/feature/auth/data/signup_response.g.dart
lib/feature/search/data/popular/popular_keyword_dto.g.dart

- 회원가입 ResponseDTO에 모든 response 필드 추가하였음 -> 회원가입 오류 픽스됨

[Feature] 회원가입DTO 필드 추가

---

lib/feature/search/data/popular/popular_keyword_dto.dart
lib/feature/search/data/popular/popular_keyword_dto.g.dart
lib/feature/search/data/popular/popular_options_dto.dart
lib/feature/search/data/popular/popular_response.dart
lib/feature/search/data/popular/popular_response.g.dart

- 인기검색어DTO에 모든 필드 추가
- 키값을 _id에서 id로 수정
search 관련DTO만 수정되었고 이건 다른 곳에 쓰이지 않으며, Search가 잘 작동하는거 확인되었기에 제가 머지를 하겠습니다.......

[Fix] 인기검색어가 로드되지 않던 문제 해결

---

lib/core/data/models/dto/product_dto.dart
lib/core/data/models/entity/product.dart
lib/feature/cart/data/cart_Item_response.dart
lib/feature/cart/data/cart_item_request.dart
lib/feature/cart/data/cart_list_item.dart
lib/feature/cart/data/cart_service.dart
lib/feature/cart/domain/cart_repository_impl.dart
lib/feature/cart/domain/repository/cart_repository.dart
lib/feature/cart/domian/repository/cart_repository.dart
lib/feature/cart/presentation/cart_module.dart
lib/feature/cart/presentation/viewmodel/cart_viewmodel.dart
lib/feature/cart/presentation/widgets/cart_tab.dart
lib/feature/cart/presentation/widgets/cart_tab_bar.dart
lib/feature/home/presentation/widgets/home_content_products.dart
lib/feature/payment/presentaion/widgets/payment_content.dart
lib/feature/preference/data/preference_service.dart
lib/feature/preference/presentation/widgets/preference_content_list.dart
lib/feature/product/data/product_service.dart
lib/feature/product/presentation/product_detail_screen.dart
lib/feature/product/presentation/widgets/product_detail_bottom.dart
lib/feature/product/presentation/widgets/product_detail_content.dart
lib/feature/product/presentation/widgets/product_item.dart

- 너무 높던 결합도 축소 및 정상적인 아키텍처 구조로 변경
- 카트 추가 기능 구현 등

[Feature] Cart 관련 수정

---

lib/core/data/models/dto/order_dto.dart
lib/core/data/models/dto/shipping_info_dto.dart
lib/feature/order/data/order_add_requset.dart
lib/feature/order/data/order_cancel_request.dart
lib/feature/order/data/order_product_dto.dart
lib/feature/order/data/order_service.dart
lib/feature/order/domain/order_repository_impl.dart
lib/feature/order/domain/repository/order_repository.dart
lib/feature/order/presentation/order_detail_screen.dart
lib/feature/order/presentation/viewmodel/order_detail_viewmodel.dart
lib/feature/order/presentation/viewmodel/order_list_viewmodel.dart
lib/feature/order/presentation/widgets/order_delivered_tab.dart
lib/feature/order/presentation/widgets/order_paid_tab.dart
lib/feature/order/presentation/widgets/order_shipping_tab.dart

- 주문취소 기능 구현
- 결제정보 연동
- addOrder 수정

[Feature] 주문취소 및 결제정보 연동

---

lib/core/data/models/dto/shipping_info_dto.dart
lib/feature/order/data/order_product_dto.dart
lib/feature/payment/domain/order_info.dart
lib/feature/payment/payment_screen.dart
lib/feature/payment/presentaion/widgets/cart_payment_content.dart
lib/feature/payment/presentaion/widgets/payment_content.dart
lib/feature/product/presentation/widgets/product_detail_bottom.dart

- ShippingInfoDTO 및 OrderProductDTO 변경 (동작이 되도록 변경)
- 주문 요청 값 전달 및 통신 성공

[Feature] 장바구니에서 주문 구현

---

lib/feature/order/data/order_service.dart
lib/feature/payment/payment_screen.dart
lib/feature/payment/presentaion/widgets/cart_payment_content.dart

[Feature] 장바구니 결제 추가

---

lib/feature/home/presentation/widgets/home_content_products.dart
lib/feature/mypage/presentation/widgets/mypage_recent_content_list.dart
lib/feature/preference/presentation/widgets/preference_content_list.dart
lib/feature/product/presentation/widgets/product_detail_content.dart
lib/feature/setting/presentation/widgets/user_info_tab.dart

- UI 일관성을 위해 상품 디테일 화면 변경
- 설정에서 바꾼 이름이 뜨도록 변경
- 상품 이미지가 무조건 1:1 비율이 되도록 변경
- 현재 카트도 변경 중이나 수정할수록 기본부터 잘못되어 있어 점점 수정해야 할 범위가 커지고 있음
- 최대한 수정은 해보겠으나 시간이 될 경우에만 PR을 올릴 것 같음

[Refactor] 상품 디테일 화면 ui 수정 등

---

lib/feature/cart/presentation/widgets/cart_list_item.dart

- 카트 리스트 UI 수정
- 카트 아이템 선택 -> 제대로 된 상품 노출 정상 구현
- 현재 장바구니 오류가 있긴하나 이전 버전 확인하니 원래 있었던 오류로, 구매할 상품 선택할 때 가끔 찾을 수 없는 상품이라고 뜨는 오류가 있는 듯 함
- 또한 가격도 비정상적으로 넘어가는 상품이 몇몇 있어 확인 필요

[Refactor] cart 리스트 화면 UI 및 선택 이벤트 수정
